In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pickle

In [4]:
data=pd.read_csv("/content/healthcare-dataset-stroke-data.csv")
data

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

# **checking all the unique values in objects**

In [6]:
print("the genders available in gender are" )
print(data['gender'].unique())

the genders available in gender are
['Male' 'Female' 'Other']

In [7]:
print("the work types availbale in the work type column")
print(data['work_type'].unique())

the work types availbale in the work type column
['Private' 'Self-employed' 'Govt_job' 'children' 'Never_worked']

In [8]:
print("the residential types are")
print(data['Residence_type'].unique())

the residential types are
['Urban' 'Rural']

In [9]:
print("smoking status of the patients are")
print(data['smoking_status'].unique())

smoking status of the patients are
['formerly smoked' 'never smoked' 'smokes' 'Unknown']



#**replacing the null character in the bmi column**

In [10]:
data['bmi'].mean()

28.893236911794666

In [11]:
data['bmi'].replace(np.nan,data['bmi'].mean() ,inplace=True)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                5110 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

# **instead of label encoding we use this factorize**

In [13]:
data['gender'],label=pd.factorize(data['gender'])
data['smoking_status'],label=pd.factorize(data['smoking_status'])
data['ever_married'],label=pd.factorize(data['ever_married'])
data['Residence_type'],label=pd.factorize(data['Residence_type'])
data['work_type'],label=pd.factorize(data['work_type'])
data

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,0,67.0,0,1,0,0,0,228.69,36.600000,0,1
1,51676,1,61.0,0,0,0,1,1,202.21,28.893237,1,1
2,31112,0,80.0,0,1,0,0,1,105.92,32.500000,1,1
3,60182,1,49.0,0,0,0,0,0,171.23,34.400000,2,1
4,1665,1,79.0,1,0,0,1,1,174.12,24.000000,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,1,80.0,1,0,0,0,0,83.75,28.893237,1,0
5106,44873,1,81.0,0,0,0,1,0,125.20,40.000000,1,0
5107,19723,1,35.0,0,0,0,1,1,82.99,30.600000,1,0
5108,37544,0,51.0,0,0,0,0,1,166.29,25.600000,0,0
5109,44679,1,44.0,0,0,0,2,0,85.28,26.200000,3,0

In [14]:
data.corr()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
id,1.000000,-0.001406,0.003538,0.003550,-0.001296,-0.013690,-0.018030,0.001403,0.001092,0.002999,-0.018551,0.006388
gender,-0.001406,1.000000,0.027300,-0.021390,-0.085749,-0.029366,-0.066212,-0.005529,-0.054213,0.025110,-0.039693,-0.009200
age,0.003538,0.027300,1.000000,0.276398,0.263796,-0.679125,-0.413270,-0.014180,0.238171,0.325942,-0.375845,0.245257
hypertension,0.003550,-0.021390,0.276398,1.000000,0.108306,-0.164243,-0.075097,0.007913,0.174474,0.160189,-0.129012,0.127904
heart_disease,-0.001296,-0.085749,0.263796,0.108306,1.000000,-0.114644,-0.058263,-0.003092,0.161857,0.038899,-0.064671,0.134914
ever_married,-0.013690,-0.029366,-0.679125,-0.164243,-0.114644,1.000000,0.375944,0.006261,-0.155068,-0.335705,0.303694,-0.108340
work_type,-0.018030,-0.066212,-0.413270,-0.075097,-0.058263,0.375944,1.000000,-0.014573,-0.068135,-0.341973,0.307774,-0.058224
Residence_type,0.001403,-0.005529,-0.014180,0.007913,-0.003092,0.006261,-0.014573,1.000000,0.004946,0.000120,-0.004656,-0.015458
avg_glucose_level,0.001092,-0.054213,0.238171,0.174474,0.161857,-0.155068,-0.068135,0.004946,1.000000,0.168751,-0.097732,0.131945
bmi,0.002999,0.025110,0.325942,0.160189,0.038899,-0.335705,-0.341973,0.000120,0.168751,1.000000,-0.230553,0.038947
smoking_status,-0.018551,-0.039693,-0.375845,-0.129012,-0.064671,0.303694,0.307774,-0.004656,-0.097732,-0.230553,1.000000,-0.066393
stroke,0.006388,-0.009200,0.245257,0.127904,0.134914,-0.108340,-0.058224,-0.015458,0.131945,0.038947,-0.066393,1.000000

In [41]:
x = data.drop(columns=['stroke','id'], axis=1)
x = x.reset_index(drop=True)
y=data['stroke']

In [45]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
model=RandomForestClassifier(random_state=42)
model.fit(x_train,y_train)
y_predict=model.predict(x_test)
accuracy = accuracy_score(y_test, y_predict)
accuracy

0.9412915851272016

In [49]:
# Pickle the trained model to a file
with open('RFmodel.pkl', 'wb') as f:
    pickle.dump(model, f)

# Load the pickled model
with open('RFmodel.pkl', 'rb') as f:
    model = pickle.load(f)

# **checking our prediction with our input**

In [50]:

# Preprocess the new input data
input_data = ['Male', 67.0, 0, 1, 'Yes', 'Private', 'Urban', 228.69, 36.6, 'formerly smoked']
input_df = pd.DataFrame([input_data], columns=['gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'Residence_type', 'avg_glucose_level', 'bmi', 'smoking_status'])

# Use pd.factorize for encoding categorical columns
input_df['gender'], _ = pd.factorize(input_df['gender'])
input_df['ever_married'], _ = pd.factorize(input_df['ever_married'])
input_df['work_type'], _ = pd.factorize(input_df['work_type'])
input_df['Residence_type'], _ = pd.factorize(input_df['Residence_type'])
input_df['smoking_status'], _ = pd.factorize(input_df['smoking_status'])

# Replace missing values in 'bmi' column with the mean
input_df['bmi'].replace(np.nan, data['bmi'].mean(), inplace=True)

# Make a prediction using the loaded model
prediction = model.predict(input_df)

print("Prediction:", prediction)

Prediction: [1]